// get_brief MCP tool (redesign P1) — fetch a Weekly Ideation Brief by
// week or latest-first. Read-only; the brief is generated by the
// Sunday cron (src/orchestrator/brief.ts), this tool only serves it.

import { sql } from 'drizzle-orm';

import type { Db } from '../../db/client.js';
import type { BriefPitch } from '../../scoring/brief.js';
import { GetBriefArgs } from '../schemas.js';

type BriefRow = {
  id: string;
  week_of: string;
  pitches: BriefPitch[];
  content_md: string;
  model: string;
  created_at: string;
  updated_at: string | null;
};

export async function getBrief(
  db: Db,
  rawArgs: unknown,
): Promise<{
  brief: {
    id: string;
    week_of: string;
    pitch_count: number;
    pitches: BriefPitch[];
    content_md: string;
    model: string;
    created_at: string;
    updated_at: string | null;
  };
}> {
  const args = GetBriefArgs.parse(rawArgs ?? {});
  const rows = args.week_of
    ? await db.execute<BriefRow>(sql`
        SELECT id, week_of, pitches, content_md, model, created_at, updated_at
        FROM briefs WHERE week_of = ${args.week_of}::date LIMIT 1
      `)
    : await db.execute<BriefRow>(sql`
        SELECT id, week_of, pitches, content_md, model, created_at, updated_at
        FROM briefs ORDER BY week_of DESC LIMIT 1
      `);
  const row = rows[0];
  if (!row) {
    throw new Error(
      args.week_of ? `no brief for week ${args.week_of}` : 'no briefs yet',
    );
  }
  return {
    brief: {
      id: row.id,
      week_of: String(row.week_of).slice(0, 10),
      pitch_count: row.pitches.length,
      pitches: row.pitches,
      content_md: row.content_md,
      model: row.model,
      created_at: row.created_at,
      updated_at: row.updated_at,
    },
  };
}
